services:
  - type: web
    name: directus-cms
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install -g directus"
    startCommand: "directus start"
    envVars:
      - key: KEY
        value: your-key
      - key: SECRET
        value: your-secret
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_SSL
        value: true
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: false
